# Generated by Django 2.0.3 on 2018-03-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password_updated_at', models.DateTimeField(null=True)),
                ('joined_at', models.DateTimeField(null=True)),
                ('has_trial', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('banned', 'Banned'), ('inactive', 'Inactive')], default='active', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
