# Generated by Django 2.2.2 on 2019-07-25 14:58

from django.db import migrations, models
import django_lifecycle


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWhenAnyPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('full_name', models.CharField(max_length=75)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.LifecycleModelMixin, models.Model),
        ),
    ]
