# Generated by Django 2.2.2 on 2019-09-28 23:24

from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.Organization'),
        ),
    ]
