# Generated by Django 2.2.8 on 2020-02-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190928_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='name_changes',
            field=models.IntegerField(default=0),
        ),
    ]
