# Generated by Django 5.1 on 2025-03-13 17:34

import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0006_useraccount_configurations"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelThatFailsIfTriggered",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
